spring.application.name=spring-gift

# ???? ?
jwt.key=testjwtkey0sf564s6df4s68fs5g4s6d4f8e4e4sd68
REST_API_KEY=???_???_??_?????
REDIRECT_URL=http://localhost:8080
AUTHORIZATION_CODE=???_???_???_?????


# h2-console
spring.h2.console.enabled=true
# db url
spring.datasource.url=jdbc:h2:mem:test
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=create

spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true