jwt.key=Yn2kjibddFAWtnPJ2AFlL8WXmohJMCvigQggaEypa5E=

REST_API_KEY=502f3fd1afaf3ffa45fdbc4bc61d14dc
REDIRECT_URL=http://localhost:8080
AUTHORIZATION_CODE=XMXIoWmM6WELjzkIGGwhYp4PdcPl0VFBxthPhZmJvCMrWHK5KyKXogAAAAQKFwtrAAABmDueKNVONYg--5I0Sw