jwt.key=Yn2kjibddFAWtnPJ2AFlL8WXmohJMCvigQggaEypa5E=

REST_API_KEY = 502f3fd1afaf3ffa45fdbc4bc61d14dc
REDIRECT_URL = http://localhost:8080
AUTHORIZATION_CODE = 3ptmzi14fBfl0TyODQ6zJ2L5iY9l01mesuATiHO0DEUtjWwJ7WJhUwAAAAQKFxTuAAABmDZqwMWBPKUF0hG4dQ